create-release:
  name: Create GitHub Release
  runs-on: ubuntu-latest
  needs: [bump-version, changelog]
  if: needs.bump-version.outputs.new-version != ''
  steps:
    - name: New Version
      env:
        NEW_VERSION: ${{ steps.bump-version.outputs.new-version }}
      run: echo "new version $NEW_VERSION"
    - name: Create Release
      id: create-release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: ${{needs.bump-version.outputs.new-version}}
        repo_token: ${{ github.token }}
        prerelease: true